### ISSUE TITLE
question about eval_mot.py

### ISSUE THREAD

**Issue by moonnyeon** [jm12138/SoccerNet_Tracking_PaddleDetection#1]
Hello, I saw the readme you posted and proceeded with learning based on fairmot_dla34_30e_1088x608.yml.

I received the data as you uploaded and have a structure like your readme's 4.3 Dataset Structure.

So, I got ./output/fairmot_dla34_30e_1088x608/model_final through learning, and when I run infer_mot.py using it, I get very good results. I am very grateful for that.

But

python tools/eval_mot.py \
     -c ./configs/snmot/fairmot/fairmot_dla34_30e_1088x608.yml \
     -o weights=./output/fairmot_dla34_30e_1088x608/model_final

Running this command gives bad results.

![Screenshot from 2023-01-17 18-23-57](https://user-images.githubusercontent.com/87063668/212859626-74d540c9-874c-4041-8d06-a5e64348b3d3.png)

But strangely, the result is like this
If you pass the --save_images option to this command as shown below,

python tools/eval_mot.py \
     -c ./configs/snmot/fairmot/fairmot_dla34_30e_1088x608.yml \
     -o weights=./output/fairmot_dla34_30e_1088x608/model_final --save_images

The results come out very well. So, it seems to me that there is a little difference between the gt of the test data and the results I output. Can you explain this?
![00002](https://user-images.githubusercontent.com/87063668/212860471-0adbba80-c243-4d83-aa89-0a9c29d0eeb5.jpg)

The first one is the gt of snmot_116.txt
1,136,520,51,135,1,-1
1,478,565,51,140,1,-1
1,565,518,48,124,1,-1
1,468,433,46,113,1,-1
1,557,302,34,84,1,-1
1,935,548,59,140,1,-1
1,981,541,69,137,1,-1
1,1061,488,40,122,1,-1
1,1096,487,64,122,1,-1
1,1288,457,53,113,1,-1
1,1387,432,32,110,1,-1
1,1419,425,37,105,1,-1
1,1433,452,65,107,1,-1
1,1461,446,33,125,1,-1
1,1457,446,27,109,1,-1
1,1479,449,29,119,1,-1
1,1498,444,23,122,1,-1
1,1511,443,42,123,1,-1
1,1527,444,44,114,1,-1
1,474,381,12,11,1,-1
2,138,521,50,134,1,-1
2,478,565,52,140,1,-1

The second is the result of eval_mot.py for snmot_116.txt.

1,1,979.3623657226562,537.5514526367188,67.99530029296875,142.71917724609375,0.8652112483978271,-1,-1,-1
1,2,1059.39111328125,487.4664306640625,50.0430908203125,125.7547607421875,0.8487852215766907,-1,-1,-1
1,3,561.3187866210938,517.5396118164062,50.31048583984375,125.93096923828125,0.8338124752044678,-1,-1,-1
1,4,469.16290283203125,562.5975952148438,63.3663330078125,146.7279052734375,0.8325880765914917,-1,-1,-1
1,5,1385.3065185546875,435.7818908691406,37.7908935546875,104.35342407226562,0.8277827501296997,-1,-1,-1
1,6,930.896728515625,545.0053100585938,67.34722900390625,141.5628662109375,0.8227060437202454,-1,-1,-1
1,7,1095.5455322265625,486.6717224121094,62.39013671875,123.30844116210938,0.8168835043907166,-1,-1,-1
1,8,137.36280822753906,521.64794921875,57.26155090332031,132.1103515625,0.7864314317703247,-1,-1,-1
1,9,1289.9215087890625,458.0888671875,54.00048828125,109.88653564453125,0.7662001848220825,-1,-1,-1
1,10,1435.694091796875,460.97503662109375,35.9664306640625,95.9007568359375,0.7223823070526123,-1,-1,-1
1,11,1524.3800048828125,447.9779968261719,43.870849609375,108.17288208007812,0.7123496532440186,-1,-1,-1
1,13,1508.180419921875,453.407470703125,47.8900146484375,109.7581787109375,0.6771827340126038,-1,-1,-1
1,14,555.231201171875,304.4537658691406,35.3944091796875,78.3070068359375,0.6704235672950745,-1,-1,-1
1,15,1454.0382080078125,449.23687744140625,44.5313720703125,118.51806640625,0.6550086736679077,-1,-1,-1
1,16,467.6395263671875,434.97662353515625,50.28375244140625,111.728271484375,0.647138237953186,-1,-1,-1
1,17,1490.5936279296875,451.5460510253906,40.251220703125,110.70571899414062,0.627478301525116,-1,-1,-1
1,18,1477.7757568359375,453.5410461425781,36.9327392578125,111.53018188476562,0.5647479295730591,-1,-1,-1

**Comment by Gintka** [comment]
got same problem. And one more problem, when add "save_images" option in the command, i got assertion error
<img width="842" alt="image" src="https://user-images.githubusercontent.com/20283535/228406427-0770022e-492e-4d5c-8232-df0af6a98387.png">
Did you solve this?

**Comment by Gintka** [comment]
> 1,5,1385.3065185546875,435.7818908691406,37.7908935546875,104.35342407226562,0.8277827501296997
got same problem. And one more problem, when add "save_images" option in the command, i got assertion error
![image](https://user-images.githubusercontent.com/20283535/228409747-4e7ec8dc-b0b7-4384-a461-74a158252f28.png)
Did you solve this?
