### ISSUE TITLE
no such file or directiry

### ISSUE THREAD

**Issue by Gintka** [jm12138/SoccerNet_Tracking_PaddleDetection#2]
安装readme.md的步骤，克隆安装之后我想跳过训练，下载你给的模型直接验证。我是这样做的：按照6.7模型推理的命令参数，把这个repo里`configs/snmot/fairmot`目录下readme.md中的模型下载了下来，是一个.pdparams文件。但是报错了，是-c参数，没有fairmot_dla34_30e_1088x608.yml。可是这个文件在configs目录下，为什么会报错呢？

**Comment by jm12138** [comment]
可以检查一下路径参数，或者参考一下 https://aistudio.baidu.com/aistudio/projectdetail/4350452?channelType=0&channel=0

**Comment by Gintka** [comment]
> 可以检查一下路径参数，或者参考一下 https://aistudio.baidu.com/aistudio/projectdetail/4350452?channelType=0&channel=0

方便邮箱什么的联系吗，谢谢您

**Comment by Gintka** [comment]
> 可以检查一下路径参数，或者参考一下 https://aistudio.baidu.com/aistudio/projectdetail/4350452?channelType=0&channel=0

在你给出的链接中实验，不管是训练还是推理，又出现了`TypeError: __init__() got an unexpected keyword argument 'heatmap_weight'
 `报错 @jm12138

**Comment by jm12138** [comment]
那可能是ppdet的版本更新了吧，可以试试切换到2.3版本看看

**Comment by Gintka** [comment]
> 

ppdet是PaddleDetection吗？我使用这个命令`python -m pip install paddlepaddle-gpu==2.3.2 -i https://mirror.baidu.com/pypi/simple`，安装了2.3版本，又弄了一遍，还是同样的错误

**Comment by jm12138** [comment]
是PaddleDetection的分支版本，不是PaddlePaddle的版本 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3

**Comment by Gintka** [comment]
> 是PaddleDetection的分支版本，不是PaddlePaddle的版本 https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.3

还是一样的 我的邮箱是xandercheung233@gmail.com 可以去邮箱说吗

**Comment by jm12138** [comment]
https://github.com/jm12138/SoccerNet_Tracking_PaddleDetection/blob/f066f34d0ef55fc94e897e6e218588dc61b41835/configs/snmot/fairmot/_base_/fairmot_dla34.yml#L26 你把配置文件里面这个配置删了试试，具体我也不知道为啥，可能是哪里更新了，然后版本没对上吧

**Comment by Gintka** [comment]
> 
问题确实出在这里！删除heatmap_weight之后，还要依次删除size_weight、offset_weight、iou_weight。然后训练就可以正常开始了，推理也正常了。谢谢大佬的耐心指导！👍PS:训练输出的最后出现了fetal error，不知道是哪里的问题，目前看来也没有影响，还是贴张图上来好了
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/20283535/227708512-e9e3a13e-c531-4eb9-a78c-ff6cd865f05d.png">
